name: Deploy intelli-secure-azure-infra

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: "Build-Infrastructure"
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Bicep File
        uses: Azure/cli@v2.2.0
        with:
          inlineScript: |
            echo "Building Bicep template"
            az bicep build --file main.bicep

      - name: What-If Deployment (Preview Changes)
        uses: Azure/cli@v2.2.0
        with:
          inlineScript: |
            echo "Running What-If analysis"
            az deployment sub what-if --location eastus --template-file ./main.bicep --parameters @parameters/dev.json


  securityScan:
    name: "Security-Scan-Analysis"
    needs: build
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: .
          soft_fail: false
          output_format: sarif

      - name: Upload SARIF report to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  manualApproval:
    name: "Manual Approval Required"
    needs: [build, securityScan]
    runs-on: ubuntu-latest
    environment:
      name: approval-dev

    steps:
      - name: Waiting For Manual Approval
        run: echo "Waiting for approval from Reviewer"


  deploy:
    name: "Deploy-Infrastructure"
    needs: manualApproval
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure
        uses: Azure/cli@v2.2.0
        with:
          inlineScript: |
            echo "Running Final Deployment"
            az deployment sub create --name intelli-secure-ddp-deploy-dev --location eastus --template-file ./main.bicep --parameters @parameters/dev.json
