name: Bicep Test WorkFlow Infra

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: "build infra"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Debug secrets before login
      - name: Debug Secret values
        run: |
          echo "AZURE_CLIENT_ID = (${{ secrets.AZURE_CLIENT_ID }})"
          echo "AZURE_TENANT_ID = (${{ secrets.AZURE_TENANT_ID }})"
          echo "AZURE_SUBSCRIPTION_ID = (${{ secrets.AZURE_SUBSCRIPTION_ID }})"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Example Bicep Deployment Command
      # - name: Deploy Bicep
      #   run: |
      #     az deployment sub what-if \
      #       --location eastus \
      #       --template-file main.bicep

