name: CI-intelli-secure-azure-infra-test-env

on:
  push:
    branches:
      - test
      - prod
env:
  ENV_NAME: ${{ github.ref_name }}                     # dev / test / prod
  PARAM_FILE: parameters/${{ github.ref_name }}.json   # dynamic param file

jobs:
  build:
    name: Deploy-Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Bicep File
        run: |
          az bicep build --file main.bicep

      - name: What-If Deployment (Preview Changes)
        run: |
          az deployment sub what-if \
            --location eastus \
            --template-file ./main.bicep \
            --parameters @$PARAM_FILE
  securityScan:
    name: Security-Scan-Analysis
    needs: build
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: ./main.bicep
          framework: bicep
          soft_fail: false
          output_format: sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
  manualApproval:
    name: Manual Approval Required
    needs: [ build, securityScan ]
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'prod' }}

    environment:
      name: approval-prod 

    steps:
      - name: Waiting For Approval
        run: "true"
  deploy:
    name: Deploy Infrastructure
    needs: [ build, securityScan ]
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure
        run: |
          az deployment sub create \
            --name intelli-secure-ddp-deploy-${{ github.ref_name }} \
            --location eastus \
            --template-file ./main.bicep \
            --parameters @$PARAM_FILE
  rollback:
    name: "Rollback Deployment"
    needs: deploy
    runs-on: ubuntu-latest
    if: failure() && github.ref_name == 'prod'

    environment: prod

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout last successful commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Rollback Deployment
        run: |
          az deployment sub create \
            --name rollback-${{ github.run_id }} \
            --location eastus \
            --template-file ./main.bicep \
            --parameters @parameters/prod.json

      - name: Rollback Completed
        run: true
