name: CI-intelli-secure-azure-infra-environments

on:
  push:
    branches:
      - main
      - dev
      - test
      - prod

env:
  ENV_NAME: ${{ github.ref_name }}
  PARAM_FILE: parameters/${{ github.ref_name }}.json

jobs:

  build:
    name: Build Bicep & Upload Artifact (MAIN)
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment: main

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Bicep â†’ main.json
        run: |
          az bicep build --file main.bicep

      - name: Upload infra artifact
        uses: actions/upload-artifact@v4
        with:
          name: infra-artifact
          path: main.json


  securityScan:
    name: Security Scan (Checkov)
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: ./main.bicep
          framework: bicep
          soft_fail: false
          output_format: sarif

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif


  manualApproval:
    name: Manual Approval (Only for PROD)
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'prod' }}
    needs: [securityScan]

    environment:
      name: approval-prod

    steps:
      - name: Waiting for Approval
        run: "true"


  deploy:
    needs: [securityScan, manualApproval]
    runs-on: ubuntu-latest
    if: github.ref_name != 'main' && needs.securityScan.result == 'success' && needs.manualApproval.result == 'success'

    environment:
      name: ${{ github.ref_name }}

    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get latest MAIN successful build run-id
        id: get_run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "blank.yml",
              branch: "main",
              status: "success"
            });
            if (!runs.data.workflow_runs.length) {
              core.setFailed("No successful MAIN build found!");
            } else {
              const runId = runs.data.workflow_runs[0].id;
              core.setOutput("run_id", runId);
            }

      - name: Download Build Artifact
        uses: actions/download-artifact@v6
        with:
          name: infra-artifact
          path: ./build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get_run.outputs.run_id }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy using Deployment Stack
        run: |
          az stack sub create \
            --name mystack-${{ github.ref_name }} \
            --location eastus \
            --template-file build/main.json \
            --parameters @parameters/${{ github.ref_name }}.json \
            --deny-settings-mode None \
            --action-on-unmanage detachAll
      


  rollback:
    name: Rollback Deployment
    needs: [deploy]
    runs-on: ubuntu-latest
    if: failure() && github.ref_name == 'prod'

    environment: main

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Get Last Successful Commit
        id: last_success
        uses: actions/github-script@v6
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "blank.yml",
              status: "success",
              branch: "main"
            });
            if (!runs.data.workflow_runs.length) {
              core.setFailed("No successful workflow run found for main branch!");
            } else {
              core.setOutput("sha", runs.data.workflow_runs[0].head_sha);
            }

      - name: Checkout Last Successful Commit
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.last_success.outputs.sha }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Rollback Deployment (Stack)
        run: |
          az stack sub create \
            --name rollbackstack-${{ github.run_id }} \
            --location eastus \
            --template-file main.bicep \
            --parameters @parameters/prod.json \
            --deny-settings-mode None \
            --action-on-unmanage detachAll 
            

      - name: Rollback Completed
        run: "true"
