name: CI-intelli-secure-azure-infra-environments

on:
  push:
    branches:
      - main
      - dev
      - test
      - prod

env:
  ENV_NAME: ${{ github.ref_name }}
  PARAM_FILE: parameters/${{ github.ref_name }}.json

jobs:

  build:
    name: Build Bicep & Upload Artifact (MAIN only)
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment: main

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build main.bicep â†’ main.json
        run: |
          az bicep build --file main.bicep --outfile main.json

      - name: Upload infra artifact
        uses: actions/upload-artifact@v4
        with:
          name: infra-artifact
          path: main.json


  securityScan:
    name: Security Scan (Checkov)
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: ./main.bicep
          framework: bicep
          soft_fail: false
          output_format: sarif

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif


  manualApproval:
    name: Manual Approval (PROD only)
    runs-on: ubuntu-latest
    if: github.ref_name == 'prod'

    environment:
      name: approval-prod

    steps:
      - run: ":"


  deploy:
    needs: [securityScan]
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'

    environment:
      name: ${{ github.ref_name }}

    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     
      - name: Get latest MAIN successful build run-id
        id: get_run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "CI-intelli-secure-azure-infra-environments.yml",
              branch: "main",
              status: "success"
            });

            if (!runs.data.workflow_runs.length) {
              core.setFailed("No successful MAIN build found!");
            } else {
              const runId = runs.data.workflow_runs[0].id;
              core.setOutput("run_id", runId);
            }

    
      - name: Download Build Artifact
        uses: actions/download-artifact@v6
        with:
          name: infra-artifact
          path: ./build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get_run.outputs.run_id }}

  
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  
      - name: Azure CLI Deploy (Run)
        run: |
          az deployment sub create \
            --location eastus \
            --template-file build/main.json \
            --parameters @parameters/${{ github.ref_name }}.json


  rollback:
    name: Rollback (PROD only)
    needs: deploy
    runs-on: ubuntu-latest
    if: failure() && github.ref_name == 'prod'
    environment: main

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Last Successful Artifact
        uses: actions/download-artifact@v4
        with:
          name: infra-artifact
          path: rollback-artifact

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Rollback Deployment
        run: |
          az deployment sub create \
            --name rollback-${{ github.run_id }} \
            --location eastus \
            --template-file rollback-artifact/main.json \
            --parameters @parameters/prod.json

